// Generated by bilt-cloud from this project's database schema. Do not edit.
// Regenerated on every schema change; edits are overwritten.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

declare module '@biltme/backend' {
  interface Database {
    public: {
      Tables: {
        daily_logs: {
          Row: {
            id: string;
            user_id: string;
            log_date: string;
            symptoms: Json;
            created_at: string;
          };
          Insert: {
            id: string;
            user_id: string;
            log_date: string;
            symptoms?: Json;
            created_at?: string;
          };
          Update: {
            id?: string;
            user_id?: string;
            log_date?: string;
            symptoms?: Json;
            created_at?: string;
          };
          Relationships: [];
        };
        health_profiles: {
          Row: {
            user_id: string;
            age: number;
            height_cm: number | null;
            weight_kg: number | null;
            condition: 'none' | 'pcos' | 'hypothyroid' | 'hyperthyroid' | 'anemia';
            medications: string | null;
            last_period_start_date: string;
            onboarding_complete: boolean;
            created_at: string;
            updated_at: string;
          };
          Insert: {
            user_id: string;
            age: number;
            height_cm?: number | null;
            weight_kg?: number | null;
            condition: 'none' | 'pcos' | 'hypothyroid' | 'hyperthyroid' | 'anemia';
            medications?: string | null;
            last_period_start_date: string;
            onboarding_complete?: boolean;
            created_at?: string;
            updated_at?: string;
          };
          Update: {
            user_id?: string;
            age?: number;
            height_cm?: number | null;
            weight_kg?: number | null;
            condition?: 'none' | 'pcos' | 'hypothyroid' | 'hyperthyroid' | 'anemia';
            medications?: string | null;
            last_period_start_date?: string;
            onboarding_complete?: boolean;
            created_at?: string;
            updated_at?: string;
          };
          Relationships: [];
        };
        lab_results: {
          Row: {
            id: string;
            user_id: string;
            result_date: string;
            tsh: number | null;
            ft4: number | null;
            lh: number | null;
            fsh: number | null;
            amh: number | null;
            hemoglobin: number | null;
            ferritin: number | null;
            attachment_name: string | null;
            attachment_mime_type: string | null;
            attachment_size_bytes: number | null;
            attachment_uri: string | null;
            created_at: string;
          };
          Insert: {
            id: string;
            user_id: string;
            result_date: string;
            tsh?: number | null;
            ft4?: number | null;
            lh?: number | null;
            fsh?: number | null;
            amh?: number | null;
            hemoglobin?: number | null;
            ferritin?: number | null;
            attachment_name?: string | null;
            attachment_mime_type?: string | null;
            attachment_size_bytes?: number | null;
            attachment_uri?: string | null;
            created_at?: string;
          };
          Update: {
            id?: string;
            user_id?: string;
            result_date?: string;
            tsh?: number | null;
            ft4?: number | null;
            lh?: number | null;
            fsh?: number | null;
            amh?: number | null;
            hemoglobin?: number | null;
            ferritin?: number | null;
            attachment_name?: string | null;
            attachment_mime_type?: string | null;
            attachment_size_bytes?: number | null;
            attachment_uri?: string | null;
            created_at?: string;
          };
          Relationships: [];
        };
        period_entries: {
          Row: {
            id: string;
            user_id: string;
            start_date: string;
            end_date: string | null;
            period_length_days: number | null;
            flow_intensity: number;
            symptoms: Json;
            created_at: string;
          };
          Insert: {
            id: string;
            user_id: string;
            start_date: string;
            end_date?: string | null;
            period_length_days?: number | null;
            flow_intensity: number;
            symptoms?: Json;
            created_at?: string;
          };
          Update: {
            id?: string;
            user_id?: string;
            start_date?: string;
            end_date?: string | null;
            period_length_days?: number | null;
            flow_intensity?: number;
            symptoms?: Json;
            created_at?: string;
          };
          Relationships: [];
        };
      };
      Views: { [_ in never]: never };
      Functions: { [_ in never]: never };
      Enums: { [_ in never]: never };
      CompositeTypes: { [_ in never]: never };
    };
  }
}
